# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_app', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='from',
            name='time_departure',
            field=models.DateTimeField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='to',
            name='price',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='to',
            name='time_arrival',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
